title: Hexagonal Matrix Module
description: Small module for building a HexMatrix data structure
theme: jekyll-theme-modernist
remote_theme: pages-themes/modernist@v0.2.0
plugins:
  - jekyll-remote-theme
    